//
//  FavoritePresenter.swift
//  MyMovies
//
//  Created by Hazem on 6/4/19.
//  Copyright (c) 2019 Hazem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritePresentationLogic:MainPresenter
{
  func presentFavoriteList(response: Favorite.Something.Response)
}

class FavoritePresenter: FavoritePresentationLogic
{
    func presentError() {
       viewController?.displayError()
    }
    
    func presentNoInternetMessege() {
        viewController?.displayNoInternet()
    }
    
    func presentLoadingState(_ state: Bool) {
        viewController?.displayLoading(state)
    }
    
    // MARK:- Load favorited
    func presentFavoriteList(response: Favorite.Something.Response) {
        var viewModel = Favorite.Something.ViewModel()
        viewModel.moviesList = response.moviesList
        viewController?.displayFavoriteMovies(viewModel: viewModel)
    }
    
  weak var viewController: FavoriteDisplayLogic?
  
  

}
