//
//  FavoriteWorker.swift
//  MyMovies
//
//  Created by Hazem on 6/4/19.
//  Copyright (c) 2019 Hazem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

class FavoriteWorker
{

    private let dataController = DataController.shared
    
    func loadFavoriteMovies(_ completion :@escaping (_ list :[LocalMovieDetails],_ error:String?) -> ()){
        let fetchReq : NSFetchRequest<LocalMovieDetails> = LocalMovieDetails.fetchRequest()
        let predicate = NSPredicate(format: "isFavorite == %@", String(describing: true))

        fetchReq.predicate = predicate
        
        if let movieDetails = try? dataController.viewContext.fetch(fetchReq) {
            if movieDetails.count > 0 {
                
                completion(movieDetails,nil)
            }
        } else {
            completion([LocalMovieDetails](),"")
        }
  }
}
