# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'MyMovies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyMovies
  pod "TMDBSwift"
  pod 'Kingfisher', '~> 4.0'
  pod 'PKHUD', '~> 5.0'
  pod 'Alamofire', '~> 4.8.2'
end
