//
//  DiscoverPresenter.swift
//  MyMovies
//
//  Created by Hazem on 6/4/19.
//  Copyright (c) 2019 Hazem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DiscoverPresentationLogic : MainPresenter
{
    func presentMoviesList(_ movies:[Discover.DiscoverMovies.Movie])
}

class DiscoverPresenter: DiscoverPresentationLogic
{
   
    weak var viewController: DiscoverDisplayLogic?
    
    // MARK: Present Movies list
    
    func presentMoviesList(_ movies:[Discover.DiscoverMovies.Movie])
    {
        var viewModel = Discover.DiscoverMovies.ViewModel()
        viewModel.moviesList = movies
        viewController?.displayMovies(viewModel: viewModel)
    }
    
    func presentError() {
        viewController?.displayError()
    }
    
    func presentNoInternetMessege() {
        viewController?.displayNoInternet()
    }
    
    func presentLoadingState(_ state: Bool) {
        viewController?.displayLoading(state)
    }
}
