//
//  DiscoverWorker.swift
//  MyMovies
//
//  Created by Hazem on 6/4/19.
//  Copyright (c) 2019 Hazem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import TMDBSwift


class DiscoverWorker {
    func fetchMoviesWith(_ request: Discover.DiscoverMovies.Request,_ results:DiscoverResponse)  {
        
        let params:String
        
        switch request {
        case .Popular:
            params =  DiscoverSortByMovie.popularity_desc.rawValue
        case .Recent:
            params =  DiscoverSortByMovie.release_date_desc.rawValue
        }
        
        DiscoverMDB.discover(discoverType: DiscoverType.movie	, params: [DiscoverParam.sort_by(params)]) {
            (clientReturn, moviesList, TvList) in
            
            if let error = clientReturn.error {
                // handle error
                print(error.localizedDescription)
                results.showError()
                return
            }
            if let apiMoviesList = moviesList {
                let appMovies = convertMovies(movieDb: apiMoviesList)
                results.showMoviesList(moviesList: appMovies)
            }
            
        }
    }
}
