//
//  DiscoverInteractor.swift
//  MyMovies
//
//  Created by Hazem on 6/4/19.
//  Copyright (c) 2019 Hazem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DiscoverBusinessLogic
{
  func loadPopularMovies()
}

protocol DiscoverDataStore
{
  //var name: String { get set }
}
protocol DiscoverResponse :class {
    func showMoviesList(moviesList:[Discover.DiscoverMovies.Movie])
    func showError()
}

class DiscoverInteractor: DiscoverBusinessLogic, DiscoverDataStore,DiscoverResponse
{
   
    
  var presenter: DiscoverPresentationLogic?
  var worker: DiscoverWorker? = DiscoverWorker()
  //var name: String = ""
  
  // MARK: Do something
  
  func loadPopularMovies()
  {
    // TODO check for internet connection here
    presenter?.presentLoadingState(true)
    worker?.fetchPopularMovies(self)
    
  }
    
    func showMoviesList(moviesList: [Discover.DiscoverMovies.Movie]) {
        presenter?.presentLoadingState(false)
        presenter?.presentMoviesList(moviesList)
    }
    
    func showError() {
        presenter?.presentLoadingState(false)
    }
    
}
