//
//  DiscoverModels.swift
//  MyMovies
//
//  Created by Hazem on 6/4/19.
//  Copyright (c) 2019 Hazem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import TMDBSwift
import ObjectMapper

enum Discover
{
  // MARK: Use cases
  
  enum DiscoverMovies
  {
    enum Request{
       case Popular,Recent
    }
    struct Movie : Mappable {
        
        
        var id :Int? 
        var title:String?
        var posterPath:String? = ""
        var backdropPath:String? = ""
        var movieRate:Double?
        
        init() {
            
        }
        init?(map: Map) {
            
        }
        
        mutating func mapping(map: Map) {
            id              <- map["id"]
            title           <- map["title"]
            posterPath      <- map["poster_path"]
            backdropPath    <- map["backdrop_path"]
            movieRate       <- map["vote_average"]
          
        }
        
    }
    struct Response {
        var apiMovies : [MovieMDB]?
    }
    struct ViewModel {
        var moviesList : [LocalMovie]?
    }
  }
}
