//
//  DiscoverModels.swift
//  MyMovies
//
//  Created by Hazem on 6/4/19.
//  Copyright (c) 2019 Hazem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import TMDBSwift

enum Discover
{
  // MARK: Use cases
  
  enum DiscoverMovies
  {
    enum Request{
       case Popular,Recent
    }
    struct Movie {
        var id :Int? 
        var title:String?
        var posterPath:String? = ""
        var backdropPath:String? = ""
        var movieRate:Double?
        
    }
    struct Response {
        var apiMovies : [MovieMDB]?
    }
    struct ViewModel {
        var moviesList : [LocalMovie]?
    }
  }
}
