//
//  MovieDetailsPresenter.swift
//  MyMovies
//
//  Created by Hazem on 6/7/19.
//  Copyright (c) 2019 Hazem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsPresentationLogic
{
  func presentSomething()
}

class MovieDetailsPresenter: MovieDetailsPresentationLogic
{
  weak var viewController: MovieDetailsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething()
  {
    let viewModel = MovieData.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
