//
//  MovieDetailsViewController.swift
//  MyMovies
//
//  Created by Hazem on 6/7/19.
//  Copyright (c) 2019 Hazem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsDisplayLogic: MainDisplayLogic
{
    func displatMovieInformation(viewModel: MovieData.ViewModel)
}

class MovieDetailsViewController: UIViewController, MovieDetailsDisplayLogic{
    
    
    @IBOutlet weak var moviePoster: UIImageView!
    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
    
    @IBOutlet weak var movieTitle: UILabel!
    
    @IBOutlet weak var movieRate: UILabel!
    
    @IBOutlet weak var movieReviewers: UILabel!
    @IBOutlet weak var movieRateAndGeners: UILabel!
    
    @IBOutlet weak var movieOverview: UILabel!
    
    private var movieDetails:MovieData.MovieInformation.MovieDetails? = nil
    var movieId:Int!
    
    var interactor: MovieDetailsBusinessLogic?
    var router: (NSObjectProtocol & MovieDetailsRoutingLogic & MovieDetailsDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = MovieDetailsInteractor()
        let presenter = MovieDetailsPresenter()
        let router = MovieDetailsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        loadMovieDetails()
    }
    
    // MARK: Load Movie Details
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func loadMovieDetails(){
        let request = MovieData.MovieInformation.Request()
        interactor?.loadMovieDetails(request: request)
    }
    
    func displatMovieInformation(viewModel: MovieData.ViewModel){
        self.moviePoster.kf.indicatorType = .activity
        self.moviePoster.kf.setImage(with: viewModel.postUrl)
        self.movieTitle.text = viewModel.movieTitle
        self.movieRate.text = viewModel.rate
        self.movieReviewers.text = viewModel.movieReviewers
        self.movieOverview.text = viewModel.movieOverView
        
    }
    
    func displayNoInternet() {
        
    }
    
    func displayLoading(_ show: Bool) {
         activityIndicator.isHidden = !show
    }
    
    func displayError() {
        
    }
    
}
