//
//  MovieDetailsWorker.swift
//  MyMovies
//
//  Created by Hazem on 6/7/19.
//  Copyright (c) 2019 Hazem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import TMDBSwift

class MovieDetailsWorker
{
    func loadMovieDetails(_ movieId:Int,_ response: MovieDetailsResponse)
    {
        MovieMDB.movie(movieID: movieId, completion: ({ (clientReturn, movieInfo) in
            if let error = clientReturn.error {
                // handle error
                print(error.localizedDescription)
                response.showError()
                return
            }
            if let details = movieInfo {
                let appMovieDetails = convertMovieDetails(details: details)
                response.showMovieDetails(appMovieDetails)
            }
            
        }))
    }
}
