//
//  MovieDetailsWorker.swift
//  MyMovies
//
//  Created by Hazem on 6/7/19.
//  Copyright (c) 2019 Hazem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import TMDBSwift

class MovieDetailsWorker
{
    func loadMovieDetails(_ movieId:Int)
    {
        MovieMDB.movie(movieID: movieId, completion: ({ (clientReturn, movieInfo) in
            if let error = clientReturn.error {
                // handle error
                print(error.localizedDescription)
            
                return
            }
            print(movieInfo?.budget)
            print(movieInfo?.homepage)
            print(movieInfo?.tagline)
            print(movieInfo?.runtime)
            print(movieInfo?.original_title)
            print(movieInfo?.overview)
            print(movieInfo?.vote_average)
            print(movieInfo?.popularity)
            
        }))
    }
}
